name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (or Python, Java, etc.)
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Replace with your desired version

      - name: Install dependencies
        run: npm install  # Replace with your package manager's install command

      - name: Run test suite
        run: npm test  # Replace with your test command

  build-and-push:
    runs-on: ubuntu-latest
    needs: test  # Ensure this job runs only if the test job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}:latest