name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            **/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run tests
        id: test
        run: bun test
        
      - name: Report test status
        if: always()
        run: |
          if [ "${{ steps.test.outcome }}" != "success" ]; then
            echo "::error::Tests failed - Cannot proceed with merge"
            exit 1
          fi

  docker:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    # Only run on main branch pushes, not PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/tpspace/thesis-fe:latest
            ghcr.io/tpspace/thesis-fe:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max